Gh 1000 Select character functionality
lambdaclass/curse_of_mirra pull request #1221
Opened 2023-11-29 15:15 UTC by tkz00

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2023-12-01 14:05 UTC, agustinesco requested changes
<img width="824" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/106101218/04a9f497-61b2-4837-85b3-e6e44b353dca">
<img width="826" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/106101218/381b9b3f-1753-44a2-98fd-b2db657eaea3">

When i try to enter the game the loading spinner stay there forever, i checked the user db has no user registered, is there something else i need to do? also i tested this with the corresponding back repo pr

2023-12-21 20:40 UTC, ncontinanza requested changes

2023-12-21 20:40 UTC, ncontinanza commented on client/Assets/Scripts/UI/UIModelManager.cs
> +
Should we remove this commented code?

2023-12-21 20:40 UTC, ncontinanza commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +            return true;
What's the use of this?

2023-12-21 20:40 UTC, ncontinanza commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +                    Debug.Log(webRequest.downloadHandler.text);
```suggestion

```

2023-12-21 21:25 UTC, BertovDev commented on client/Assets/Scripts/CharactersManager.cs
> +    public bool IsAvaibleCharacter(CoMCharacter character)
Right!

2023-12-21 21:26 UTC, BertovDev commented on client/Assets/Scripts/LobbyConnection.cs
> +                    this.playerCount = (int)lobbyEvent.AmountOfPlayers;
This is a merge error, good catch

2023-12-21 21:28 UTC, BertovDev commented on client/Assets/Scripts/UI/UIModelManager.cs
> +
Yess

2023-12-21 21:34 UTC, BertovDev commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +            return true;
This is to implement a custom certificate validation scheme. But i believe we dont want it.

2023-12-21 21:42 UTC, ncontinanza approved these changes

2023-12-22 16:00 UTC, AngieDutra approved these changes
This PR has this [bug](https://github.com/lambdaclass/curse_of_mirra/issues/1302) if more than one character is available. Will do a PR fixing this asap

2023-12-22 16:00 UTC, merged