[GH-905] User creation on title screen
lambdaclass/curse_of_mirra pull request #1237
Opened 2023-12-01 19:46 UTC by tkz00

Works towards completing #905 

## Motivation

We need the player to have a registered user to store information about they.

## Summary of changes

In the loading screen after the title screen scene it's verified if there is a user in the backend associated with the device_id of the client, if there is not a user will be created.

Also in that check modifications have been added to check if Brazil server is responding (or the server which is default in that moment), and if it isn't, automatically start pointing towards localhost server. (If the loading spinner in title screen never disappears it is probable Brazil is unavailable and the localhost server isn't running)

## How has this been tested?

To test this PR correctly it is better to run the backend locally to have more visibility of changes and ability to edit.

To target the local server you need to edit the `_defaultServerIp` field of `SelectServerIP.cs` to "AAAA" (or anything random), so it doesn't target Brazil.

- Check a user is created in title screen: be sure to not have users with your device ID in your local database and go through until main screen scene, there if you check your database, you should see a new user with your device_id.
- If there already is a user in the database with your device_id, then no new user should be created.

## Test additions / changes

No tests have been added or updated.

## Checklist
- [X] I have tested the changes locally.
- [X] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2023-12-04 14:29 UTC, agustinesco requested changes

2023-12-04 14:29 UTC, agustinesco commented on client/Assets/Scripts/UI/TitleScreenController.cs
> +        SetLoadingScreen(true);
I think the `PlayButton/0` method is not doing anything right?

2023-12-04 14:33 UTC, agustinesco submitted a review, later dismissed
LGTM! tested on localhost and the user creation is working as expected!

2023-12-04 15:23 UTC, mFragaBA requested changes

2023-12-04 15:23 UTC, mFragaBA commented on client/Assets/Scripts/Utils/Utils.cs
I think it would be nice to have a BackendUtils.cs or similar so the requests to the backend logic doesn't get mixed up with the game logic itself

2023-12-04 15:23 UTC, mFragaBA commented on client/Assets/Scripts/UI/TitleScreenController.cs
> +                        PlayButton();
If the server's down, wouldn't this end up in an endless loop?

2023-12-04 16:21 UTC, tkz00 commented on client/Assets/Scripts/UI/TitleScreenController.cs
> +                        break;
Added the message and fixed the infinite loop problem.

2023-12-04 16:22 UTC, tkz00 commented on client/Assets/Scripts/Utils/Utils.cs
> +
Removed the certificates assignation, continues to work well.

2023-12-04 16:22 UTC, tkz00 commented on client/Assets/Scripts/Utils/Utils.cs
> +            SelectServerIP.GetServerIp().Contains("10.150.20.186")
Added the load tests servers.

2023-12-04 16:26 UTC, tkz00 commented on client/Assets/Scripts/Utils/Utils.cs
Moved the server connection logic to `ServerUtils.cs`. In the future it would be nice to have a static class with a generic request method that takes the route, http method and parameters, to avoid having a method for each request needed.

2023-12-06 14:28 UTC, mFragaBA commented on client/Assets/Scripts/Utils/Utils.cs
> +
Nice!

2023-12-06 14:28 UTC, mFragaBA commented on client/Assets/Scripts/Utils/Utils.cs
Agreed!

2023-12-14 17:20 UTC, agustinesco requested changes

2023-12-14 17:20 UTC, agustinesco commented on client/Assets/Scripts/UI/TitleScreenController.cs
> +        }
What's the purpose of this while cicle?

2023-12-14 17:20 UTC, agustinesco commented on client/Assets/Scripts/UI/TitleScreenController.cs
> +                        default:
Don't we also need a `playNowButton.EnableButton();` here?

Also if you are turning off the loading screen and enabling the play button on every switch case maybe you can put both actions outside of the switch

2023-12-14 17:20 UTC, agustinesco commented on client/Assets/Scripts/UI/TitleScreenController.cs
> +                            playNowButton.EnableButton();
same as above

2023-12-14 17:20 UTC, agustinesco commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +        )
Can this if statment be simplified with an any statment? for what i can see the method `GetServerIp` returns an string, could we match that with any of the options? somethig like 
```
        List<String> servers = new List<String>{"localhost", "10.150.20.186", "168.119.71.104", "176.9.26.172"};
        if ( servers.Any((ip) => SelectServerIP.GetServerIp() == ip))
```

2023-12-14 20:55 UTC, BertovDev commented on client/Assets/Scripts/UI/TitleScreenController.cs
> +                        default:
You are right

2023-12-14 21:03 UTC, BertovDev commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +        )
Sure!, this change improve the code readability but it make it more efficient? What do you think?

2023-12-15 15:48 UTC, agustinesco commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +        )
I think i'll be the same, we had 4 comparisons before the change , and now we have a list traverse of 4 elements with n comparisons

2023-12-15 15:52 UTC, tvillegas98 commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +        )
We could improve efficiency by using a HashSet instead of a vector

2023-12-18 21:38 UTC, agustinesco submitted a review, later dismissed
LGTM!

2023-12-18 21:49 UTC, AngieDutra requested changes
When I finish a game and want to start another match the LobbyConnection is missing and i cannot do so

2023-12-18 21:49 UTC, AngieDutra commented on client/Assets/Images/UI/loading-spinner.png
This should be set to the size stablished by the team in Notion. For this sprite that is 512. I would also move these two sprites to a "Loading" folder

2023-12-19 16:31 UTC, BertovDev commented on client/Assets/Images/UI/loading-spinner.png
Sure thing!

2023-12-19 18:54 UTC, AngieDutra approved these changes
Nice work!

2023-12-19 21:38 UTC, AngieDutra approved these changes
Really good job on this PR! LGTM ✨

2023-12-19 21:39 UTC, agustinesco approved these changes
Great! nice work @BertovDev  and nice catch there @AngieDutra

2023-12-19 21:40 UTC, merged