Fix spawn effect
lambdaclass/curse_of_mirra pull request #1252
Opened 2023-12-06 23:04 UTC by BertovDev

Closes #[issue]

## Motivation

Currently the spawn effect was desactivated. With this we activate and desactive it for all players in the init of the game.

## Summary of changes

Changed CharacterBase activateSpawnFeedback method to ToggleSpawnFeedback
Re-created the logic activation in CustomLevelManager `CameraCinematic` method

## How has this been tested?

Start a game you should see the spawnfeedback once at that time and not ever again.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2023-12-07 14:58 UTC, agustinesco requested changes
The spawn effect seems to be working as expected! nice.
I just have 1 question and some comments regarding the code.

With this change we are losing the spawn sounds, is this okey?

2023-12-07 14:58 UTC, agustinesco commented on client/Assets/Scripts/CharacterBase.cs
>      }
Why are we keeping this code if we're not using it anymore?

2023-12-07 14:58 UTC, agustinesco commented on client/Assets/Scripts/CustomLevelManager.cs
> +                    character.characterBase.ToggleSpawnFeedback(true, character.PlayerID);
Why not changing the `spawnFeedback` here?
```suggestion
                    character.characterBase.spawnFeedback.SetActive(true);
```

The same goes for the function call below

2023-12-12 14:24 UTC, agustinesco requested changes
The sounds seems to be working as expected but whenever i enter a match i get this error
<img width="1092" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/106101218/d4a46ae6-f6f8-40df-888c-10db999afa76">

2023-12-12 14:24 UTC, agustinesco commented on client/Assets/Scripts/CharacterBase.cs
> +    public void ToggleSpawnFeedback(bool value, string id)
Can we rename the var value to something that indicate what we're receiving?? something like `activateSound` or `activateFeedback`

2023-12-12 15:40 UTC, BertovDev commented on client/Assets/Scripts/CharacterBase.cs
> +    public void ToggleSpawnFeedback(bool value, string id)
NIce catch, i will change it.

2023-12-12 15:49 UTC, BertovDev commented
> The sounds seems to be working as expected but whenever i enter a match i get this error <img alt="image" width="1092" src="https://private-user-images.githubusercontent.com/106101218/289885525-d4a46ae6-f6f8-40df-888c-10db999afa76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTYxNDAsIm5iZiI6MTcwMjM5NTg0MCwicGF0aCI6Ii8xMDYxMDEyMTgvMjg5ODg1NTI1LWQ0YTQ2YWU2LWY2ZjgtNDBkZi04ODhjLTEwZGI5OTlhZmE3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxNTQ0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTllNTc1NjgyNWY0ZDYzZWE5ZjFkNWU4OTdmMDNjZTU2NDJlYzk0ZTQ4N2Q0OTg1YzY5MzY1NjUzNzNiZTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wfJoFabZ0BbDuQOLwmO-d4co0zb1Q4YjaiDnRM9Bpqk">

This message is totally expected. It happends beucause in this PR I changed the audio listener from the camera to the player, so until the characters are not created you will have this message send. Nothing to worry about and good that you notice it,

2023-12-12 15:57 UTC, agustinesco commented
> > The sounds seems to be working as expected but whenever i enter a match i get this error <img alt="image" width="1092" src="https://private-user-images.githubusercontent.com/106101218/289885525-d4a46ae6-f6f8-40df-888c-10db999afa76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTYxNDAsIm5iZiI6MTcwMjM5NTg0MCwicGF0aCI6Ii8xMDYxMDEyMTgvMjg5ODg1NTI1LWQ0YTQ2YWU2LWY2ZjgtNDBkZi04ODhjLTEwZGI5OTlhZmE3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxNTQ0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTllNTc1NjgyNWY0ZDYzZWE5ZjFkNWU4OTdmMDNjZTU2NDJlYzk0ZTQ4N2Q0OTg1YzY5MzY1NjUzNzNiZTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wfJoFabZ0BbDuQOLwmO-d4co0zb1Q4YjaiDnRM9Bpqk">
> 
> This message is totally expected. It happends beucause in this PR I changed the audio listener from the camera to the player, so until the characters are not created you will have this message send. Nothing to worry about and good that you notice it,

After talking about this we think that this is only a message and we should ignore it, you can read more about it [here](https://forum.unity.com/threads/there-are-no-audio-listeners-in-the-scene-thats-actually-fine-right.384596/)

2023-12-12 15:58 UTC, agustinesco submitted a review, later dismissed

2023-12-12 17:17 UTC, ncontinanza requested changes

2023-12-12 17:17 UTC, ncontinanza commented on client/Assets/Scripts/CharacterBase.cs
> +                0.01f
We could have this value as a private constant, such as we did with the minimum volume in ToggleAudio.cs

2023-12-12 17:19 UTC, ncontinanza reviewed
Also, there's a cut in the game music during the "preparing battle" screen. The music stops, and after this screen it keeps on playing were it left

2023-12-12 18:20 UTC, BertovDev commented on client/Assets/Scripts/CharacterBase.cs
> +                0.01f
Done!

2023-12-12 18:50 UTC, ncontinanza approved these changes
LGTM!

2023-12-12 22:19 UTC, agustinesco approved these changes
LGTM!

2023-12-12 22:19 UTC, merged