New Uma model and animations
lambdaclass/curse_of_mirra pull request #1291
Opened 2023-12-19 16:46 UTC by BertovDev

Closes #1276 

## Motivation

New Uma animations 

## Summary of changes

1. Add new Animations and Model
2. Change mainscreen and characterInfo animations display from Victory to Radiance
3. Change `UIModelManager` character animation functionality

## How has this been tested?

To test it add "Uma" To the enableCharacter list in MainScreenManager script

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2023-12-21 19:57 UTC, agustinesco requested changes

2023-12-21 19:57 UTC, agustinesco commented on client/Assets/Scripts/UI/UIModelManager.cs
> +            ? clips.Single(clip => clip.name == "GR_VeilOfRadiance").length / 2
Why not renaming the animation "GR_VeilOfRadiance" to "victory" if we want to use it as victory animation? we could also duplicate it

2023-12-21 19:57 UTC, agustinesco commented on client/Assets/Scripts/UI/UIModelManager.cs
> +        string animationName = modelClone.name.Contains("Uma") ? "Radiance" : "Victory";
same as above

2023-12-21 20:05 UTC, agustinesco commented
https://github.com/lambdaclass/curse_of_mirra/assets/106101218/6dbdbe19-ee63-4746-b136-dbc22354ab47

While i tested this pr i noticed some issues in the character selection screen, lets work on them on different prs since this one only adds the uma character:
- I think the characters available should be sorted first and the not yet available second
- If i select uma as the screen is taking me to muflus
- Every time i change characters i got an unity exception

2023-12-21 20:13 UTC, agustinesco commented
When i enter a match as uma i'm  getting these errors: 
<img width="689" alt="image" src="https://github.com/lambdaclass/curse_of_mirra/assets/106101218/39fbb1e3-10ea-41de-9bf0-18da67c95b16">
<img width="641" alt="image" src="https://github.com/lambdaclass/curse_of_mirra/assets/106101218/cefb9702-75f5-48cb-a12c-c1478e5f03e1">

2023-12-21 20:33 UTC, agustinesco commented
and one last thing, the animations for uma doesn't have the flag "Has model animation" as true, so she is not doing it.

for the sake of testing i used this [backend branch](https://github.com/lambdaclass/game_backend/pull/107) to test this pr so i was able to hit

2023-12-21 21:09 UTC, BertovDev commented on client/Assets/Scripts/UI/UIModelManager.cs
> +            ? clips.Single(clip => clip.name == "GR_VeilOfRadiance").length / 2
We only want to use the "GR_VeilOfRadiance" as victory animation in the showcase of the characters (mainscreen and characterInfo). In the endgame animation we want to show the `Victory` animation not `GR_VeilOfRadiance`. Finally we also use GR_VeilOfRadiance as the animation for the skill1.

2023-12-21 21:11 UTC, BertovDev commented
> Screen.Recording.2023-12-21.at.17.01.28.mov
> 
> While i tested this pr i noticed some issues in the character selection screen, lets work on them on different prs since this one only adds the uma character:
> 
>     * I think the characters available should be sorted first and the not yet available second
> 
>     * If i select uma as the screen is taking me to muflus
> 
>     * Every time i change characters i got an unity exception

This is fixed in #1000

2023-12-21 21:20 UTC, BertovDev commented
> When i enter a match as uma i'm getting these errors: <img alt="image" width="689" src="https://private-user-images.githubusercontent.com/106101218/292310032-39fbb1e3-10ea-41de-9bf0-18da67c95b16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxOTMzMTcsIm5iZiI6MTcwMzE5MzAxNywicGF0aCI6Ii8xMDYxMDEyMTgvMjkyMzEwMDMyLTM5ZmJiMWUzLTEwZWEtNDFkZS05YmYwLTE4ZGE2N2M5NWIxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQyMTEwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjQ5ZWU4YWEzZjkwNjhkZTg0MDczYWFjMTk5ZTc0ZjRiNzA3OGIxOWFkMzg3ZjNmZGNhYTFhYWMxNmM0ZDVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YnG_Ue3iQJrUAjnmuPa8qguA_45UgjBGklhWFCVgwjo"> <img alt="image" width="641" src="https://private-user-images.githubusercontent.com/106101218/292310122-cefb9702-75f5-48cb-a12c-c1478e5f03e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxOTMzMTcsIm5iZiI6MTcwMzE5MzAxNywicGF0aCI6Ii8xMDYxMDEyMTgvMjkyMzEwMTIyLWNlZmI5NzAyLTc1ZjUtNDhjYi1hMTJjLWMxNDc4ZTVmMDNlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQyMTEwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDk1YTAwOTc0OWJhOWVhODk2OThhZWRhNzA1ODQ2MWNiN2FkOTAyZTI4Mjk5ZjdlZjkxMDgwYWE4NjYyZTZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3BPAjHpadyPv6MP_Fee-gnDlDMOQKxuR0gJCuZ59S5w">
> 
> and this one when i receive damage: <img alt="image" width="825" src="https://private-user-images.githubusercontent.com/106101218/292310775-9c57bd38-eaa0-45c2-88be-33692e1a49ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxOTMzMTcsIm5iZiI6MTcwMzE5MzAxNywicGF0aCI6Ii8xMDYxMDEyMTgvMjkyMzEwNzc1LTljNTdiZDM4LWVhYTAtNDVjMi04OGJlLTMzNjkyZTFhNDlhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQyMTEwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzhkNWY3MDM2ZDJjZjVmNjk4MjFkM2IyZjdmMjhkMThiYmZlNDNkNTVlMzc0NTI0YmE3NWYwZGZlMmQyNDdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tx34jJ-OYMl91iY62l7SjFjfub2NB0yPH4yHpiKMKus">

Awesome catch! pushed the fix!

2023-12-21 21:48 UTC, agustinesco commented on client/Assets/Scripts/UI/UIModelManager.cs
> +            ? clips.Single(clip => clip.name == "GR_VeilOfRadiance").length / 2
oh okey, maybe in the future we could add a new skill to the model to do in both the characters and the mainscreen right? (not in this pr)

2023-12-21 21:56 UTC, agustinesco commented
Great work! we're almost there, i just noticed one more errors that i think we should fix

When any uma dies i got this error
<img width="646" alt="image" src="https://github.com/lambdaclass/curse_of_mirra/assets/106101218/9e4e4e6f-e45c-4444-b24e-992b7932134a">

2023-12-21 22:00 UTC, BertovDev commented
> Great work! we're almost there, i just noticed one more errors that i think we should fix
> 
> When any uma dies i got this error <img alt="image" width="646" src="https://private-user-images.githubusercontent.com/106101218/292324929-9e4e4e6f-e45c-4444-b24e-992b7932134a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxOTYwODgsIm5iZiI6MTcwMzE5NTc4OCwicGF0aCI6Ii8xMDYxMDEyMTgvMjkyMzI0OTI5LTllNGU0ZTZmLWU0NWMtNDQ0NC1iMjRlLTk5MmI3OTMyMTM0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQyMTU2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTE4OTE5NTFmZTE3NWEyYjE3YTU4YmRkYjUwYWNlMjc0ZTE5MjY2MjY5NzE0ZjRjZTM5YWMzZDJhNDE3NGNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q3CC1OScpMV2U6OrK8Igb1XcxYHcbkO2I82LqrfUSic">


Done!

2023-12-21 22:08 UTC, agustinesco submitted a review, later dismissed
LGTM! great work

2023-12-22 14:22 UTC, ncontinanza requested changes
Looking great! I think that the UI Icon for the killfeed is missing, by adding that we're good to go

2023-12-22 22:21 UTC, ncontinanza approved these changes
LGTM! Just notice that until https://github.com/lambdaclass/game_backend/pull/107 is not fixed and merged, it won't be possible to use Uma in a battle.

2024-01-04 20:34 UTC, agustinesco approved these changes
LGTM! tested on local and the model seems great!

2024-01-04 20:34 UTC, merged