Preparing battle
lambdaclass/curse_of_mirra pull request #1296
Opened 2023-12-19 20:50 UTC by AngieDutra

Closes #1288 

## Motivation

The preparing for battle sequence was outdated style wise

## Summary of changes

![reference - screen 1](https://github.com/lambdaclass/curse_of_mirra/assets/82987608/b189f80e-6304-4453-a7df-fdaf85fb3ba4)
![reference - screen 2](https://github.com/lambdaclass/curse_of_mirra/assets/82987608/ab8a8aeb-5043-4305-b907-ba6a164ca28b)
![reference - screen 3](https://github.com/lambdaclass/curse_of_mirra/assets/82987608/bae6a37c-53b3-4012-9b90-6fa9a29bf22a)

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-01-22 18:49 UTC, BertovDev requested changes
I really love this, just a few corrections and things that I notice.

When you are walking with your character the camera moves a little bit foward and then when you stop it pan back to your character.


Uploading Grabación de pantalla 2024-01-22 a la(s) 15.45.27.mov…

2024-01-22 18:49 UTC, BertovDev commented on client/Assets/Scripts/UI/PrepareForBattleAnimations.cs
I believe we can avoid the multiples coroutines used in this script with the implementations Dotween provide us ( Append interval to add intervals at the end of the sequence and onComplete Callback to execute code at completion) . 

I recreated the `CoinDisplayAnimation` to test if it works and it did. It will be somethink like this:

```
void CoinDisplayAnimation(GameObject objectToAnimate, float originalScale)
    {
        Sequence stickerSequence = DOTween.Sequence();
        stickerSequence
            .Append(objectToAnimate.GetComponent<CanvasGroup>().DOFade(1, .3f))
            .Insert(0, objectToAnimate.transform.DOScale(originalScale + .05f, .3f))
            .Append(objectToAnimate.transform.DOScale(originalScale, .3f))
            .PrependInterval(.2f)
            .SetEase(Ease.InQuad)
            .AppendInterval(1f)
            .onComplete = () =>
        {
            AnimationCallback(objectToAnimate);
        };
    }

    void AnimationCallback(GameObject objectToAnimate)
    {
        objectToAnimate.GetComponent<Animator>().Play("Animation", 0, 0.0f);
    }
```
    
 With this we can avoid using too many coroutines simultaneously, as excessive context switching can lead to performance issues.What do you think?

2024-01-22 22:10 UTC, AngieDutra commented on client/Assets/Scripts/UI/PrepareForBattleAnimations.cs
I think this is a great approach! Good one

2024-01-23 20:32 UTC, BertovDev requested changes
One last suggestion. I believe it would be better to have the folder with all the assets outside BattleUI folder. Doing this we can create another SpriteAtlas and assign the folder to it.

With this we can modulate more each SpriteAtlas and do not have only one with all the assets.

2024-01-23 20:34 UTC, AngieDutra commented on client/Assets/Scripts/UI/PrepareForBattleAnimations.cs
> +                    .StartFollowing();
Sure, will do

2024-01-24 21:12 UTC, BertovDev approved these changes

2024-01-25 18:14 UTC, mgrunwaldt approved these changes
LGTM. One small comment for the future: I don't think the prepare for battle player image should be different from the character list image. The cost / benefit doesn't work for this

2024-01-25 18:14 UTC, merged