Arrow buttons fix
lambdaclass/curse_of_mirra pull request #1304
Opened 2023-12-22 16:17 UTC by AngieDutra

Closes #1302 

## Motivation

In character info, if more than one player is available and you press the arrows and keep your finger there the action won't stop being trigger. This PR fixes that.

## Summary of changes

Add in CharactersManager.cs "H4ck" in availableCharacterNames list and then go to characters info scene. If you press down and hold over the arrows the action should not be trigger

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2023-12-22 16:23 UTC, BertovDev submitted a review, later dismissed

2023-12-22 17:58 UTC, agustinesco requested changes
The bug of the character change is fixed now but when you hold the arrow a little bit and then release it stays small



https://github.com/lambdaclass/curse_of_mirra/assets/106101218/0b62bfd5-9de0-4cda-99fc-8a5d0f29ba80

2023-12-22 20:31 UTC, agustinesco requested changes
Now the same bug still present and the arrows doesn't go back to their original size :(

https://github.com/lambdaclass/curse_of_mirra/assets/106101218/80171fe8-3b72-450e-956d-d78ae7bd30f0

2024-01-16 14:41 UTC, AngieDutra commented
Due to too many updates in main I thought it would be best to fix this in a new [updated branch](https://github.com/lambdaclass/curse_of_mirra/pull/1331)

2024-01-16 14:41 UTC, closed without merging