GoogleSignIn - Iteration 1 - SignIn/SingOut/SignInWithCached - Android and iOS
lambdaclass/curse_of_mirra pull request #1347
Opened 2024-01-25 19:44 UTC by BertovDev

Closes #961 

## Motivation

Implement GoogleSignIn so players can link their google acoounts to the game.

## Summary of changes

- Added GoogleSignIn plugin
- Created `GoogleSignInController` script to controll the SingIn/SingOut/SingInWithCache
- Added funcionality to the Signin button in TittleScreen
- For now we are storing the google information in the PlayersPrefs. Further Iteration it will be stored in our DB.
- Implemented cancelation method when the request takes too long.
- Make it work in Android and iOS
- Created Google OAuth console credentials and app.

## How has this been tested?

This can only be tested in mobile, whether it's a simulator (not unity simulator) or a real phone.

1. Press SignIn, a google popup should appear. Choose your account
2. Press play  you should see your google name displayed in the top left corner in Mainscreen
3. Close the App, re-open it. You should be logged with your last account entered.
4. SignOut. Now if you close and re-open no account should be appear as logged
5. SignIn again with any account you want.

Next steps:

- Add .env for credentials
- Handle Errors
- Relationate Google credentials to user in the DB
- How to re-authenticate the user data in the backend
- Change Domains

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-01-26 18:18 UTC, AngieDutra requested changes
Nice work! Just a few comments:
- Delete SignInSample folder from the repo
- I recommend creating a folder to organize all the files needed for the sign in to work
- I also got an error building the game in my phone:
![Screenshot_20240126_150826_client](https://github.com/lambdaclass/curse_of_mirra/assets/82987608/311c0e68-ff38-4a17-9ec3-59e617fb8b0d)

2024-01-26 18:39 UTC, BertovDev commented
> Nice work! Just a few comments:
> 
>     * Delete SignInSample folder from the repo
> 
>     * I recommend creating a folder to organize all the files needed for the sign in to work
> 
>     * I also got an error building the game in my phone:
>       ![Screenshot_20240126_150826_client](https://private-user-images.githubusercontent.com/82987608/300075720-311c0e68-ff38-4a17-9ec3-59e617fb8b0d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyOTQ2MzgsIm5iZiI6MTcwNjI5NDMzOCwicGF0aCI6Ii84Mjk4NzYwOC8zMDAwNzU3MjAtMzExYzBlNjgtZmYzOC00YTE3LTllYzMtNTllNjE3ZmI4YjBkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE4Mzg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMjE4NGM1NjJhYWNlYjllMDRkMDMyZDFkNDk0N2ZjOTU4MGUxOGVjZTA2NGMyOWYzNjYwOWY4MDg0Y2UxOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bPJyhJmtWKkqU-bsK7VMytV_kyxK0wmuG1kx3maxffc)

Update:

I did the build in her phone but with my computer and it works. So its probably some build configuration. I will check it now

2024-02-01 14:48 UTC, BertovDev commented
Reminder: This is working fine. I would be good to test it and make a build in another computer to finally check if it is a build configuration issue.

2024-05-02 17:21 UTC, AminArria commented
Will this work on Unity deskptop?

2024-05-09 20:31 UTC, Nico-Sanchez commented on client/Assets/Scenes/TitleScreen.unity
> +  webClientIdGoogle: 529212382177-822ukg0eeufi7pivtk1dpatqveqlqord.apps.googleusercontent.com
Is this necessary? Can we remove it?

2024-05-10 18:22 UTC, AngieDutra commented
I thested this PR, but I could check if I actually signed in or not. The text in title was still showing guest. Also, when I came back to change the server instead of sign out it was still saying sign in

2024-05-14 16:11 UTC, AngieDutra reviewed
Awesome! But if I return to title screen the log in UI state is nor preserved
![Screenshot_20240514_130908_client](https://github.com/lambdaclass/curse_of_mirra/assets/82987608/672858c2-12eb-45e3-a68b-ad7a0bc2ce6c)
![Screenshot_20240514_130921_client](https://github.com/lambdaclass/curse_of_mirra/assets/82987608/16f14543-2f86-4dd7-b438-e2539b0e7cf8)

2024-05-14 21:54 UTC, AngieDutra approved these changes
Tested in Android builds and is working as expected. Congrats!

2024-05-15 16:44 UTC, tkz00 approved these changes
Looks good!

2024-05-15 18:48 UTC, AngieDutra approved these changes
Awesome!

2024-05-15 18:48 UTC, merged