Change ips to dns urls
lambdaclass/curse_of_mirra pull request #1386
Opened 2024-02-02 15:57 UTC by BertovDev

## Motivation

Change IPs to dns URL

## Summary of changes

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-02-02 15:58 UTC, AngieDutra submitted a review, later dismissed
LGTM ✨

2024-02-05 13:29 UTC, manucamejo requested changes
@BertovDev please, do the same thing on this file `client/Assets/Scripts/ServerConnection.cs`

2024-02-05 21:23 UTC, AngieDutra approved these changes
Tested and worked fine

2024-02-07 15:53 UTC, manucamejo approved these changes

2024-02-07 15:53 UTC, merged