New character info screen
lambdaclass/curse_of_mirra pull request #1395
Opened 2024-02-03 00:06 UTC by AngieDutra

## Motivation

The character info screen was outdated

## Summary of changes

- deleted old character selection screen
- applied new styles and functionalities

![reference (7)](https://github.com/lambdaclass/curse_of_mirra/assets/82987608/d812acf3-a0eb-40b1-92a0-8b09a9a8e085)

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-02-05 18:13 UTC, BertovDev requested changes
Nice and just a few comments. Select button is not working due the missing component I mencioned above.

2024-02-05 18:13 UTC, BertovDev commented on client/Assets/Scripts/UI/CharacterInfoManager.cs
> +        StartCoroutine(rotateUIModel.GetModel());
This is not necessary you are already calling it the Start method of `RotateUIModel` Script..

2024-02-05 18:13 UTC, BertovDev commented on client/Assets/Scripts/UI/CharacterInfoManager.cs
> +    private RotateUIModel rotateUIModel;
Same for this. We can remove it.

2024-02-05 18:38 UTC, AngieDutra commented on client/Assets/Scenes/CharacterInfo.unity
<img width="718" alt="Captura de pantalla 2024-02-05 a la(s) 15 36 52" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/df8f83d3-a6f0-4fc8-9b4a-1e88e7a04f1f">

I'm actually fixing the scene itself. It was broken in main. If things were working properly I should be able to checkout from main this scene and have all working properly. Instead this is the result. Therefore, these changes are vital

2024-02-06 19:14 UTC, lotuuu approved these changes
Looks good to me! Tablet resolution is a bit weird but I'm guessing that's not on our priority list right now. All phone resolutions looked ok
<img width="1200" alt="Screen Shot 2024-02-06 at 16 10 18" src="https://github.com/lambdaclass/curse_of_mirra/assets/31993243/9d3ee295-033b-4a46-b52d-18ef90defe83">

2024-02-06 19:28 UTC, merged