Improve Damage Feedback
lambdaclass/curse_of_mirra pull request #1407
Opened 2024-02-06 18:21 UTC by BertovDev

Closes #1344 

## Motivation

Improve damage feedback from a instant fash to a fade. 

## Summary of changes

Change DamageFeedback prefab and add fader object to CameraUI

## How has this been tested?

Start a game and receive damage.

Disclaimer: The damage when you receive it from the danger zone could be too much. This is because we are dealing the damage from the backend in every tick. We either left this until the backend is fixed or make a temporary workaround in the client.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-02-07 17:56 UTC, BertovDev commented
Update: Now I added some Bump effect to the healthBar. Again IGNORE the pink squares. I did not charge the asset yet.

https://github.com/lambdaclass/curse_of_mirra/assets/62818001/dd4fff13-1615-4dfd-a533-c4c66a932529

2024-02-07 20:00 UTC, mgrunwaldt requested changes
The effect for the health bar is the same if we receive damage that when the natural healing heals us, for me this is really confusing

2024-02-07 20:31 UTC, BertovDev commented
> The effect for the health bar is the same if we receive damage that when the natural healing heals us, for me this is really confusing

You are right, already fixed. Also I notice that the bar started scaled. So i manage to create a fix, activating the bump effect only on first damage.

2024-02-09 16:51 UTC, mgrunwaldt approved these changes

2024-02-09 17:59 UTC, AngieDutra approved these changes

2024-02-09 17:59 UTC, AngieDutra commented
Will wait till backend is implemented to merge this but the frontend is great!

2024-02-09 21:53 UTC, merged