Stamina Mechanic
lambdaclass/curse_of_mirra pull request #1418
Opened 2024-02-09 19:12 UTC by BertovDev

Closes #985 

## Motivation

Show stamina in client

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-02-09 19:13 UTC, BertovDev commented
Iteration 1

https://github.com/lambdaclass/curse_of_mirra/assets/62818001/503dedbb-5a0c-494e-a5c2-b71ce9edc98a

2024-02-15 20:48 UTC, BertovDev commented
New assets, indicator and animations

https://github.com/lambdaclass/curse_of_mirra/assets/62818001/366f98ae-ddc0-46df-a9e3-298a52caa733

2024-02-16 19:05 UTC, BertovDev commented
https://github.com/lambdaclass/curse_of_mirra/assets/62818001/523d8a54-5ebb-4ea6-a437-96a03835ccf9

2024-02-19 14:48 UTC, agustinesco requested changes

2024-02-19 14:48 UTC, agustinesco commented on client/Assets/Scripts/StaminaManager.cs
> +    private ulong maxStamina;
I think we should delete this variable since we're not using it, the same goes for `staminaInterval` and `animated`

2024-02-19 15:11 UTC, BertovDev commented on client/Assets/Scripts/StaminaManager.cs
> +    private ulong maxStamina;
Suree

2024-02-19 17:03 UTC, agustinesco approved these changes
LGTM!

2024-02-20 15:51 UTC, mgrunwaldt submitted a review, later dismissed
LGTM!

2024-02-20 16:35 UTC, agustinesco approved these changes
LGTM!

2024-02-20 16:44 UTC, agustinesco approved these changes

2024-02-20 18:02 UTC, mgrunwaldt approved these changes

2024-02-20 18:02 UTC, merged