Send movement changes
lambdaclass/curse_of_mirra pull request #1428
Opened 2024-02-14 03:05 UTC by manucamejo

## Motivation

We need to send to the backend only changes instead of 1 message every 30ms

## Summary of changes

- Improve client prediction

## How has this been tested?

Test it on Brazil and Europe. Check if the movement feels fluent or not.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [x] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [ ] Tested in Android.

2024-02-14 14:44 UTC, BertovDev requested changes
This is working awesome and just a small comment.

2024-02-14 14:44 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +                            gameEvent.PlayerTimestamps[player.Id],
We are keep sending `PlayerTimestamps` even when the player is dead.

2024-02-14 14:44 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +                            gameEvent.PlayerTimestamps[player.Id],
We should add a conditional  `&& serverPlayerUpdate.Player.Health > 0` in the line `252`.

2024-02-14 15:09 UTC, BertovDev reviewed
Tested on Android S23. Server Brazil and Europe.

2024-02-15 14:00 UTC, BertovDev submitted a review, later dismissed

2024-02-19 15:17 UTC, agustinesco commented on client/Assets/Scripts/ClientPrediction.cs
> +        for (int i = 0; i < pendingPlayerInputs.Count; i++)
I you're just using the index to get  the pending input you could use a foreach here

2024-02-19 15:48 UTC, agustinesco commented on client/Assets/Scripts/Battle.cs
> +                    && useClientPrediction && serverPlayerUpdate.Player.Health > 0
I think you can also check the player status here

2024-02-19 15:52 UTC, agustinesco approved these changes
LGTM! 
To tests this i used toxi-proxy to give myself some lag and it's working amazing! 
0ms observations: there's no difference between the main branch, the movement is smooth and accurate
150ms observations: The movement is smooth but at the end of the movement you can see the player move a bit back without animation
300ms observations: The movement is smooth but at the end of the movement you can see the player walks a bit back
1500ms observations: The client movement seems smooth but at the end of the movement you can see the player walks in the same place for a while

2024-02-19 16:02 UTC, BertovDev approved these changes
LGTM!!

2024-02-19 16:02 UTC, merged