Improved tapping ux
lambdaclass/curse_of_mirra pull request #1467
Opened 2024-02-21 19:47 UTC by saugon

## Summary of changes
- Input indicators (arrow and area) are displayed only when the player drags the knob.
- Changed Uma's ultimate control type to Tap instead of Direction.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-02-21 20:46 UTC, BertovDev requested changes
Sneak should be direction and veil tap.

2024-02-21 20:57 UTC, BertovDev submitted a review, later dismissed
Good!

2024-02-21 21:25 UTC, mgrunwaldt requested changes
I think h4ck's ulti should be cone, not arrow

2024-02-22 00:32 UTC, mgrunwaldt approved these changes

2024-02-22 00:33 UTC, marco-paulucci approved these changes

2024-02-22 00:33 UTC, merged