Implement valtimer ultimate
lambdaclass/curse_of_mirra pull request #1473
Opened 2024-02-21 21:46 UTC by agustinesco

Test with this [Backend PR](https://github.com/lambdaclass/mirra_backend/pull/298)

2024-02-27 22:22 UTC, BertovDev commented
Tested on android s23 working fine.

2024-02-27 22:23 UTC, BertovDev commented
We should tweak the config to adjust the range and radius of the ability

2024-03-07 14:17 UTC, Nico-Sanchez requested changes
It doesn't seem to work accurately. The ultimate's pool object doesn't spawn where I'm aiming and the visual representation size is not the same as the one received from the backend.
This can be seen by a character getting pulled in to a pool that it's not colliding yet in the visuals.

2024-03-07 17:49 UTC, BertovDev commented
> It doesn't seem to work accurately. The ultimate's pool object doesn't spawn where I'm aiming and the visual representation size is not the same as the one received from the backend. This can be seen by a character getting pulled in to a pool that it's not colliding yet in the visuals.

You are right! all adjust are done!

2024-03-07 21:02 UTC, Nico-Sanchez commented on client/Assets/Scripts/Skills/Skill.cs
> +        skillInfo.skillCircleRange = radius;
Shouldn't we rename this? Looks awkward to have a variable called "range" and assign a "radius" to it.

2024-03-07 21:07 UTC, BertovDev commented on client/Assets/Scripts/Skills/Skill.cs
> +        skillInfo.skillCircleRange = radius;
Yess, nice catch

2024-03-07 21:08 UTC, BertovDev commented on client/Assets/Scripts/Skills/Skill.cs
> +        skillInfo.skillCircleRange = radius;
Also renamed another vars.

2024-03-07 21:50 UTC, BertovDev commented
Draft till we decide what to do with the scaled textures inputs.

2024-03-11 15:00 UTC, BertovDev commented
> Draft till we decide what to do with the scaled textures inputs.

We will continue with this textures for now. Implementing a new one in another iteration.

2024-03-11 15:06 UTC, Nico-Sanchez submitted a review, later dismissed

2024-03-11 19:47 UTC, AngieDutra submitted a review, later dismissed
Tested on Desktop and Android and it's looking awesome!

2024-03-11 19:49 UTC, AngieDutra reviewed
I'll say this prefab is changing on use and shouldn't
<img width="519" alt="Captura de pantalla 2024-03-11 a las 16 48 20 p  m" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/ae2960c2-a236-4279-90d4-e9d322a58da9">

2024-03-11 21:09 UTC, AngieDutra approved these changes
Tested with a match between two desktops and worked just fine ✨ No prefabs modified in the process

2024-03-11 21:10 UTC, ncontinanza approved these changes
LGTM!

2024-03-11 21:49 UTC, Nico-Sanchez approved these changes

2024-03-11 21:49 UTC, merged