Fix direction when moving
lambdaclass/curse_of_mirra pull request #1489
Opened 2024-02-23 00:12 UTC by manucamejo

Closes #[issue]

## Motivation

The player's direction was wrong because added a threshold to the magnitude of the movement between frames.

## Checklist
- [x] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-02-23 14:24 UTC, agustinesco requested changes
The initial direction of the players is correct now but if i dash while holding the movement key the dash seems wrong

2024-02-23 18:25 UTC, manucamejo commented
> The initial direction of the players is correct now but if i dash while holding the movement key the dash seems wrong

Thanks, Agus, you're right.
I just fixed it.

2024-02-24 03:35 UTC, agustinesco approved these changes
LGTM!

2024-02-24 04:00 UTC, BertovDev approved these changes

2024-02-24 04:00 UTC, merged