Update prepare for battle
lambdaclass/curse_of_mirra pull request #1495
Opened 2024-02-23 18:42 UTC by BertovDev

Closes #1456 

## Motivation

Update prepare for battle screen

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-02-23 18:46 UTC, jazimp commented
I reviewed the visual implementation and it's looking good!

2024-02-26 14:48 UTC, AngieDutra requested changes
I noticed the UI label was misplaced. However neither the reference or implementation works for all images without covering the character's face. I talked with @jazimp and she said the label should be placed in the character's name container anchored in the middle right side of it.

This PR implementation:
<img width="1088" alt="Captura de pantalla 2024-02-26 a las 11 38 44 a  m" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/22776fcb-13d2-47ac-9745-bb6de3814352">

The reference:
![306440100-ce401fef-b1cf-4e56-aa52-9b1e61b59873](https://github.com/lambdaclass/curse_of_mirra/assets/82987608/be1109a9-a021-4628-8d50-6074ddc79fa0)

2024-02-26 14:48 UTC, AngieDutra commented on client/Assets/Images/UI/BattleUI/PrepareForBattle/New/1(1).png
Try to avoid naming the images with numbers

2024-02-26 14:50 UTC, AngieDutra commented on client/Assets/Images/UI/BattleUI/PrepareForBattle/New/1(1).png
Also, please review all the new images max sizes.
<img width="307" alt="Captura de pantalla 2024-02-26 a las 11 47 17 a  m" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/8aeccfd9-4c38-42ed-ae59-0c38677c50b1">

2024-02-27 14:24 UTC, AngieDutra commented
The team requested a las minute fix: the current text "Be the last standing" should be -> "Be the last one standing". Checked with @BertovDev and he will add this here. I'll wait for that commit to review this PR

2024-02-27 16:12 UTC, AngieDutra approved these changes
LGTM
✔️ Text was changed
✔️ Valtimer's victory animation was fixed (thought it was going to be fixed [here](https://github.com/lambdaclass/curse_of_mirra/pull/1496) but it works"
✔️ Each character's icon in prepare screen is correct
✔️ The you label is fixed
✔️ Files were correctly added in the heriarchy
✔️ Sprite sizes were fixed
✔️ Tested with more players and the label is correctly placed
Just a note: I believe the "you" label is not working visually anymore so in a near future we should rethink how we are highlighting the player's own character. Already talked with @jazimp about this. Created issue #1517 regarding this

2024-02-27 16:39 UTC, AngieDutra approved these changes

2024-02-28 14:24 UTC, agustinesco commented
> LGTM ✔️ Text was changed ✔️ Valtimer's victory animation was fixed (thought it was going to be fixed [here](https://github.com/lambdaclass/curse_of_mirra/pull/1496) but it works) ✔️ Each character's icon in prepare screen is correct ✔️ The you label is fixed ✔️ Files were correctly added in the heriarchy ✔️ Sprite sizes were fixed ✔️ Tested with more players and the label is correctly placed Just a note: I believe the "you" label is not working visually anymore so in a near future we should rethink how we are highlighting the player's own character. Already talked with @jazimp about this. Created issue #1517 regarding this

I think the "You" label is a path while we implement the username and user registration system, when we implement this the user will be able to recognize himself with his username right?

2024-02-28 14:35 UTC, agustinesco requested changes
Is there any reason to add the new images to a folder called "New"? we think the images should just be on the "PrepareForBattle" Folder

Also lets rename the images to delete the number, for example:
`client/Assets/Images/UI/BattleUI/PrepareForBattle/New/H4ck(1).png`
Should be 
`client/Assets/Images/UI/BattleUI/PrepareForBattle/New/H4ck.png`

2024-02-28 14:48 UTC, agustinesco commented
Tested the prepare for battle animation and is working correctly with every character both in the unity editor and in an android build! should be ready to merge when we fix the files names and folders

2024-02-28 14:59 UTC, AngieDutra commented
Good one! While you are at this maybe you could delete the "new" folder and move the images inside that to the parent folder, according to our desired heriarchy

2024-02-28 21:12 UTC, agustinesco approved these changes
🪨

2024-02-28 21:40 UTC, AngieDutra approved these changes
✔️ Did a final asset check and works just fine

2024-02-28 21:41 UTC, merged