Refactor healing feedback
lambdaclass/curse_of_mirra pull request #1540
Opened 2024-03-04 16:45 UTC by AngieDutra

Closes #1530 

## Motivation

The healing feedback was being trigger when a match started. This is not ideal behavior.

## Summary of changes

The healing feedback was a parent to the vfx since before it's children were particle systems. Now we have only one vfx healing feedback so I deleted the vfx child and added the vfx to the HealFeedback game object.
In addition, the vfx was set to play on enable. This resulted on it showing at the beginning with the character load in the scene. I set the vfx to be played only by code.
<img width="333" alt="Captura de pantalla 2024-03-04 a la(s) 13 42 55" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/66972b18-d286-4f03-a67c-56805283d341">

## How has this been tested?

- Start a game and check if the healing feedback is working as expected. 
- To further check this, open any character prefab with the scene opened too. The feedback won't show. If this were to be done in main the healing feedback would show
<img width="1107" alt="Captura de pantalla 2024-03-04 a la(s) 13 41 13" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/e1179f6a-5c5a-4881-8986-2950c8fff870">

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-03-06 15:01 UTC, BertovDev approved these changes

2024-03-06 19:59 UTC, Nico-Sanchez requested changes
The healing feedback animation is still being triggered for Muflus. Tested with all the characters, but only Muflus is still showing it when he spawns.

2024-03-07 18:13 UTC, BertovDev requested changes
Niceee, just a small change and we are done!

2024-03-07 18:13 UTC, BertovDev commented on client/Assets/Scripts/CustomLevelManager.cs
> +
You can simplify this in `GeneratePlayers` method with this:

`newPlayer.CharacterHealth.CurrentHealth = player.Player.Health;`

You can write this above the line `173` in `CustomLevelManager`

2024-03-07 20:00 UTC, AngieDutra commented on client/Assets/Scripts/CustomLevelManager.cs
> +
Done!

2024-03-07 20:06 UTC, BertovDev approved these changes

2024-03-08 14:52 UTC, Nico-Sanchez approved these changes

2024-03-08 14:52 UTC, merged