Main settings
lambdaclass/curse_of_mirra pull request #1552
Opened 2024-03-07 22:13 UTC by AngieDutra

Closes #1013 

## Motivation

We didn't have a settings splash in main screen

## Summary of changes

![reference (10)](https://github.com/lambdaclass/curse_of_mirra/assets/82987608/d49c7f61-c9d6-4fd3-b250-4296e7c1b6d6)

## How has this been tested?

Try out the sfx and music toggles and sliders and see if they apply the settings to you game.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-03-25 15:55 UTC, BertovDev requested changes
This is pretty well directed and minor changes have to be made. Also merge main to this.

2024-03-25 15:55 UTC, BertovDev commented on client/Assets/Scripts/UI/Settings/ToggleAudio.cs
>          soundManager.SetVolumeSfx(SFX_VOLUME);
This is resetting the sfx volumen

We should implement the same we have for music volume but for SFX

2024-03-25 15:55 UTC, BertovDev commented on client/Assets/Scripts/UI/Settings/ToggleAudio.cs
> +    }
We can simplify this with

```
    private void ToggleUIState(bool isUnMuted){
        muteButtonImage.enabled = isUnMuted;
        textSoundState.text = isUnMuted ? offState : onState;
    }
```
Also the way you are triggering this, you do not need the `unmutedSprite` and `mutedSprite` anymore

2024-03-25 15:55 UTC, BertovDev commented on client/Assets/Scripts/UI/Settings/ToggleAudio.cs
> +        }
With the change I suggested:

```
 if (IsMuted(channel))
        {
            ToggleUIState(false);
        }
        else
        {
            ToggleUIState(true);
        }
```

2024-03-25 15:55 UTC, BertovDev commented on client/Assets/Scripts/UI/Settings/ToggleAudio.cs
> +            UpdateMutedUIState();
```
         ToggleUIState(true);
        }
        if (volumeSlider.value == MUTED_VOLUME)
        {
             ToggleUIState(false);
        }
```

2024-03-25 15:55 UTC, BertovDev commented on client/Assets/Scripts/UI/Settings/ToggleAudio.cs
> +            UpdateMutedUIState();
```
     if (IsMuted(channel))
        {
            PlaySound();
            ToggleUIState(true);
        }
        else
        {
            SilenceSound();
            ToggleUIState(false);
        }
```

2024-03-25 15:55 UTC, BertovDev commented on client/Assets/Scripts/UI/Settings/ToggleButton.cs
> +        if (battle != null)
This is not working as expected, when you toggle this on, leave the game and re-enter the UI and the functionality are not matching.

2024-03-25 16:01 UTC, AngieDutra commented on client/Assets/Scripts/UI/Settings/ToggleAudio.cs
> +    }
This was implemented as it is to have a more versatile code if two toggles are visually represented different. (In case one toggle button does have a mute sprite) But it's not the case for the current UI buttons so I could delete this until it happens 👍🏼

2024-03-25 18:22 UTC, AngieDutra commented
All done! @BertovDev ✨

2024-03-25 18:45 UTC, AngieDutra commented
I'll add some transparent text effects requested by @jazimp and I'll leave this ready again soon

2024-03-25 21:06 UTC, jazimp commented
I reviewed the screenshots and functionality (from Angie's computer) and I don't see any differences from the reference! Good job 👍

2024-03-26 14:40 UTC, BertovDev requested changes
Volume slider seems not to be working fine. This can be about the Update method in `VolumeController` class. Let me know if you need help to debug. 

https://github.com/lambdaclass/curse_of_mirra/assets/62818001/c6786e6d-75d3-4eac-af46-1c3dcd99ab37

2024-03-26 14:40 UTC, BertovDev commented on client/Assets/Scripts/UI/Settings/ToggleAudio.cs
> +        muteButtonImage.sprite = unmutedSprite;
With this you are re-assigning the sprite by code and it is already assigned in unity. Seems not to be necessary IMO.

I will delete the unmutedSprite variable.

2024-03-26 14:40 UTC, BertovDev commented on client/Assets/Scripts/UI/Settings/ToggleAudio.cs
>      }
Simplify this creating a method single method and reusing it.

```
  private void ControlChannelTrack(MMSoundManager.MMSoundManagerTracks track, float baseVolume){
        if (!IsMuted(channel))
            {
                float currentTrackVolume = soundManager.GetTrackVolume(
                    track,
                    false
                );
                float trackVolume =
                    currentTrackVolume != baseVolume ? currentTrackVolume : baseVolume;
                unmutedVolume = volumeSlider ? volumeSlider.value : trackVolume;
            }
            else
            {
                unmutedVolume = volumeSlider ? volumeSlider.value : baseVolume;
            }
    }
```

then

   ```
 public void SetUnmutedVolume(MMSoundManager.MMSoundManagerTracks channel)
    {
        switch (channel)
        {
            case MMSoundManager.MMSoundManagerTracks.Music:
                ControlChannelTrack(channel, MUSIC_VOLUME);
                break;
            case MMSoundManager.MMSoundManagerTracks.Sfx:
                ControlChannelTrack(channel, SFX_VOLUME);
                break;
        }
    }
```

2024-03-26 15:14 UTC, AngieDutra commented on client/Assets/Scripts/UI/Settings/ToggleAudio.cs
> +        muteButtonImage.sprite = unmutedSprite;
It's easier to implement this though code in the future. Felt more implementation friendly but will delete if it doesn't make sense to apply now

2024-03-26 17:01 UTC, AngieDutra commented
The video you sent was happening because the start value was, in main, set from the ui implementation. To avoid this issue, now and in the future, I set this value from the code

2024-03-26 18:13 UTC, saugon commented
I have a small request. Could the active tab default to the first one every time the settings are opened? For example, if I open the settings from the main screen, switch to the server tab, and then close it, the next time I open it, the server tab is still active

2024-03-26 21:07 UTC, AngieDutra commented
I could make this addition work in regards the tabs but could quickly reset the scroll position

2024-03-27 17:48 UTC, BertovDev submitted a review, later dismissed
Awesome work

2024-03-27 18:42 UTC, saugon commented on client/Assets/Scripts/UI/Settings/ToggleAudio.cs
> +        if (IsMuted(channel))
This If statement (and several others in this PR) could be simplified with something like:

`ToggleUIState(!IsMuted(channel));`

Or, for better readability:
```
toggleValue = !IsMuted(channel);
ToggleUIState(toggleValue);
```

2024-03-27 19:12 UTC, AngieDutra commented
Okey. I'll push this change and a fix to the toggle problem @BertovDev mentioned. (Starting the match with muted music and being able to toggle it in game)

2024-03-27 19:59 UTC, BertovDev submitted a review, later dismissed
Really nice

2024-03-27 19:59 UTC, AngieDutra commented
Just tested in Android build and in Unity build ✨

2024-03-27 21:47 UTC, saugon approved these changes
Great job!

2024-03-27 21:51 UTC, BertovDev approved these changes

2024-03-27 21:51 UTC, merged