Implement player name
lambdaclass/curse_of_mirra pull request #1578
Opened 2024-03-12 19:30 UTC by BertovDev

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-03-12 21:46 UTC, jazimp commented
Bauti showed me how the design implementation looks, and it looks good! It has my visual approval 👍🏻

2024-03-13 16:26 UTC, agustinesco reviewed
The name is getting outside of the label in the main screen 
<img width="351" alt="image" src="https://github.com/lambdaclass/curse_of_mirra/assets/106101218/d70f1cd0-fb4a-4cb0-8662-5391b2b6b6d3">

2024-03-13 16:28 UTC, agustinesco commented
The game client players doesn't have their name
<img width="221" alt="image" src="https://github.com/lambdaclass/curse_of_mirra/assets/106101218/d21d692d-0380-4d9b-b9d3-7218101b9c40">

2024-03-13 16:29 UTC, agustinesco commented
i think we should include the names in the prepare for battle screen too 
<img width="934" alt="image" src="https://github.com/lambdaclass/curse_of_mirra/assets/106101218/db0c77d5-61a9-4c77-a283-75003c38abb0">

2024-03-13 16:32 UTC, agustinesco commented
I think we should kind of adjust the text size on the kill feed to support longer names? 
<img width="352" alt="image" src="https://github.com/lambdaclass/curse_of_mirra/assets/106101218/a3eb9ad2-b289-4e64-8112-11cae41b63a6">

2024-03-13 16:40 UTC, agustinesco requested changes
The killfeed is working as expected and the name is being displayer correctly! let's fix the previous comment and we're good to go!

i've tested this pr in both an android release and in the unity client

2024-03-14 15:38 UTC, BertovDev commented
> The game client players doesn't have their name <img alt="image" width="221" src="https://private-user-images.githubusercontent.com/106101218/312542894-d21d692d-0380-4d9b-b9d3-7218101b9c40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjQ4NzgsIm5iZiI6MTcxMDQyNDU3OCwicGF0aCI6Ii8xMDYxMDEyMTgvMzEyNTQyODk0LWQyMWQ2OTJkLTAzODAtNGQ5Yi1iOWQzLTcyMTgxMDFiOWM0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxMzU2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTk4YjFlYTQzM2NiNzk0OTg0NWJiODc3YjQ3MTc4NWI2MDQ3M2U2ODdmOTEzYzZmMWRkZjYwODVmODljMDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TrLN9_WSyagALyPG5MhKG2Tee3rlfHOwetUAMGGiYtw">

This was a think I forgot in the backend repo. All fixed!

2024-03-14 21:42 UTC, agustinesco approved these changes
LGTM! 

Not blocking but for long names the "you" tag is being overlap, this tag was temporal? 

<img width="296" alt="image" src="https://github.com/lambdaclass/curse_of_mirra/assets/106101218/d75dc256-3655-4e00-91fe-74c02a1af7e9">

2024-03-14 23:37 UTC, saugon commented on client/Assets/Scripts/UI/EndGame/EndGameManager.cs
> +            // defeaterPlayerName.text = GetDefeaterPlayerName();
Let's add this too  (it may need a reference visual from @jazimp)

2024-03-15 14:06 UTC, jazimp commented on client/Assets/Scripts/UI/EndGame/EndGameManager.cs
> +            // defeaterPlayerName.text = GetDefeaterPlayerName();
![refe name killed by](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/6c48a493-b304-4c67-9278-b1ea43a2f65b)
Font: Source Sans 3, variable: Regular 

Disclaimer: This is the quick solution to get it working now. In the future, a design will be proposed that includes all the match result information.

2024-03-15 20:04 UTC, BertovDev commented on client/Assets/Scripts/UI/EndGame/EndGameManager.cs
> +            // defeaterPlayerName.text = GetDefeaterPlayerName();
<img width="529" alt="Screenshot 2024-03-15 at 17 04 05" src="https://github.com/lambdaclass/curse_of_mirra/assets/62818001/39b6463f-c0ce-48fc-b5c2-caf81cc11f0f">

2024-03-15 20:09 UTC, jazimp commented on client/Assets/Scripts/UI/EndGame/EndGameManager.cs
> +            // defeaterPlayerName.text = GetDefeaterPlayerName();
It has my visual approval 👍🏻

2024-03-18 12:51 UTC, AngieDutra reviewed
If we are adding the character name back to the game, aren't we supposed to add the button to change this name too? The game object for that is in title screen and the game object is called ChangeNameContainer

2024-03-18 13:25 UTC, BertovDev commented
> If we are adding the character name back to the game, aren't we supposed to add the button to change this name too? The game object for that is in title screen and the game object is called ChangeNameContainer

I think it has a point but at the same time I would not continue adding complexity to this PR. We can move on and add it to another one. I like the suggestion indeed , what do you think to take advice from the team and maybe create an issue about it.

2024-03-18 14:10 UTC, BertovDev commented
> Talked with our TL who suggested an issue is created for this game object to be an option within settings in main screen as soon as the PR adding that settings screen is in main. Do you mind creating that issue?

Suree

2024-03-18 17:25 UTC, manucamejo approved these changes

2024-03-18 17:29 UTC, AngieDutra approved these changes
Tested on Android and worked like a charm ✨

2024-03-18 17:29 UTC, merged