Item pick up feedback
lambdaclass/curse_of_mirra pull request #1588
Opened 2024-03-13 21:22 UTC by AngieDutra

Closes #1557 

## Motivation

The items feedback should be in each character to easily detect which player picked the item up
The UI also needed a fix

## Summary of changes

This PR:
- Changes how the vfx feedback shows
- Fixes the UI

## How has this been tested?

KNOWN ISSUE: #1587 Pick Up feedback shows 2 times in specific cases

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [ ] Tested in Android.

2024-03-14 17:13 UTC, BertovDev requested changes
Left some comments, the useItemFeedback was working only once per player.

2024-03-14 17:13 UTC, BertovDev commented on client/Assets/Scripts/CharacterFeedbacks.cs
> +        }
This is causing to only make the feedback appears once. To make this work correctly you can do:

` didPickUp = state;`

2024-03-14 17:13 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +
Do not do this here. You can do this in `CharacterFeedbackManager.cs` Update method.

2024-03-18 15:06 UTC, BertovDev approved these changes
Awesome!!

2024-03-18 16:44 UTC, agustinesco approved these changes
LGTM! tested on an android build and it looks amazing!

2024-03-18 16:45 UTC, merged