Fix movement after dying the player + camera still move
lambdaclass/curse_of_mirra pull request #1606
Opened 2024-03-19 14:57 UTC by BertovDev

Closes #1571 

## Motivation

After death players still can move due to client movement.

## Summary of changes

Restrict movement only when player health from Entity is > 0

## How has this been tested?

- Start a game with +1 player, force your death while walking
- When you are death the player should stop walking.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-03-20 21:22 UTC, AngieDutra requested changes
@tkz00, @BertovDev and I were playing. I, AN (Android build), killed them both but they both redirected to another player, also called AN (Unity desktop)

2024-03-21 18:03 UTC, tkz00 approved these changes
Looks good

2024-03-21 18:05 UTC, AngieDutra requested changes
Since this is prompt to error I would change this locally but you could also accept my changes and test this after

2024-03-21 18:05 UTC, AngieDutra commented on client/Assets/Scripts/UI/KillFeedManager.cs
> +    public void SetcurrentTrackedPlayer(ulong newcurrentTrackedPlayer){
```suggestion
    public void SetCurrentTrackedPlayer(ulong newCurrentTrackedPlayer){
```

2024-03-21 18:05 UTC, AngieDutra commented on client/Assets/Scripts/UI/KillFeedManager.cs
> +        this.currentTrackedPlayer = newcurrentTrackedPlayer;
```suggestion
        this.currentTrackedPlayer = newCurrentTrackedPlayer;
```

2024-03-21 18:05 UTC, AngieDutra commented on client/Assets/Scripts/CustomLevelManager.cs
> +            KillFeedManager.instance.SetcurrentTrackedPlayer(playerToFollow.Id);
```suggestion
            KillFeedManager.instance.SetCurrentTrackedPlayer(playerToFollow.Id);
```

2024-03-21 18:05 UTC, AngieDutra commented on client/Assets/Scripts/CustomLevelManager.cs
> +        ulong currentTrackedPlayer = KillFeedManager.instance.GetcurrentTrackedPlayer();
```suggestion
        ulong currentTrackedPlayer = KillFeedManager.instance.GetCurrentTrackedPlayer();
```

2024-03-21 18:05 UTC, AngieDutra commented on client/Assets/Scripts/UI/KillFeedManager.cs
> +    public ulong GetcurrentTrackedPlayer(){
```suggestion
    public ulong GetCurrentTrackedPlayer(){
```

2024-03-21 18:12 UTC, BertovDev commented
> Since this is prompt to error I would change this locally but you could also accept my changes and test this after

All done!

2024-03-21 18:32 UTC, tkz00 requested changes
During playtest this was shown to not work as expected.

2024-03-21 18:35 UTC, AngieDutra requested changes
Tested on Android and Unity desktop but It didn't work as expected. Sometimes it wouldn't redirect to the killer but to the first player in the list

2024-03-22 16:36 UTC, AngieDutra approved these changes
Awesome. Exited to restore this feature!

2024-03-22 16:37 UTC, tkz00 approved these changes
Looks good

2024-03-22 16:37 UTC, merged