Fix countdown time
lambdaclass/curse_of_mirra pull request #1607
Opened 2024-03-19 17:20 UTC by BertovDev

Closes #1601 

## Motivation

The prepare for battle animation was still playing even when the gameStart countdown from backend already finished. 

## Summary of changes

Adjust times, and coroutines exit statement. 

## How has this been tested?

Start different games, corroborate all of them starts in the correct time. You can check this with the danzer zone timer in the matchStats container. It should appear as 35 seconds (That is the value it has in the config)

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-03-20 14:57 UTC, agustinesco requested changes
This solution is not working as expected, if i start a match with my phone and the unity client i'm having a difference of ~3 seconds almost every time

2024-03-20 19:38 UTC, BertovDev commented
> This solution is not working as expected, if i start a match with my phone and the unity client i'm having a difference of ~3 seconds almost every time

I believe this is due to the graphic power of the devices. Since we are not having in count the graphic power of each phone and we do not know when each player phone already charged everything

2024-03-20 19:39 UTC, BertovDev commented
> > This solution is not working as expected, if i start a match with my phone and the unity client i'm having a difference of ~3 seconds almost every time
> 
> I believe this is due to the graphic power of the devices. Since we are not having in count the graphic power of each phone and we do not know when each player phone already charged everything

Maybe we should wait until each player is done charging the graphic things.

2024-03-20 21:31 UTC, AngieDutra commented
I tested this and worked fine in Android build. I'm waiting for the @agustinesco to check his change request until I approve this

2024-03-20 22:05 UTC, agustinesco approved these changes
LGTM! when my phone load fast enough the timers are synced, maybe we could work in a future for a fix for lower end phones

Tested on an android build and the unity client and created an issue to fix the timers for the lower end phones #1616

2024-03-21 13:14 UTC, AngieDutra approved these changes
Awesome! Tested on android build too ✨

2024-03-21 13:15 UTC, merged