UI character implementation
lambdaclass/curse_of_mirra pull request #1608
Opened 2024-03-19 17:51 UTC by AngieDutra

Closes #1397
Closes #1605
Closes #1604 
Closes #1475 

## Motivation

Bugs in main:
- Rotation speed was too high
- Two ways of rendering the models in the UI (one in main and the other in character info) where used instead of one prefab. This resulted in two UX. mainly noticeable in the rotation feature. In main the rotation was within the character and in character info the rotation could be trigger from the sides
- When the user pressed the character, then dragged the finger but for the release of it they returned to the original position the link would trigger. This is not ideal behavior.

## Summary of changes
Solved issues:
- Rotation speed was adjusted
- Now we have 1 prefab used to render UI models
- The code was refactored to have a clean and readable code

In addition:
- Adjusted the main screen and characters info model position to be the same in both screens and don't have weird offsets from screen to screen

## How has this been tested?

- Use the rotation feature in character info and in main screen
- Use the link feature in main screen to go to character info
- Try to use it as random as possible to find any issues I could've missed

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [ ] Tested in Android.

2024-03-19 19:20 UTC, BertovDev requested changes
Not working as expected. 
https://github.com/lambdaclass/curse_of_mirra/assets/62818001/5d5b046b-1c02-4396-896d-5649b9aedeab

2024-03-19 22:38 UTC, BertovDev reviewed
This is awesome and just a few comments.
In my opinion the height of the rotate container is too much since it feels weird to touch the part of the screen marked in the photo and rotate the character.

<img width="1248" alt="Screenshot 2024-03-19 at 19 36 15" src="https://github.com/lambdaclass/curse_of_mirra/assets/62818001/68b3b94d-271c-4301-973b-45d635872bfa">

2024-03-19 22:39 UTC, BertovDev commented on client/Assets/Scripts/UI/ModelLink.cs
> +    private const float MIN_DIFFERENCE = 10.0f;
What is this value referencing?

2024-03-19 22:39 UTC, BertovDev commented
Do we really need the Canvas Group component in the click GameObject?

2024-03-19 22:58 UTC, AngieDutra commented on client/Assets/Scripts/UI/ModelLink.cs
> +    private const float MIN_DIFFERENCE = 10.0f;
The margin of difference allowed between the eventData pressed and released

2024-03-19 23:02 UTC, AngieDutra commented
> Do we really need the Canvas Group component in the click GameObject?

Yes. The button has an image to be clickable. An image always goes attached with a CanvasGroup as a Unity rule
<img width="300" alt="Captura de pantalla 2024-03-19 a la(s) 8 00 49 p  m" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/07c1edfd-9ce9-4ee9-91ad-590492a94342">

2024-03-20 14:01 UTC, BertovDev approved these changes
This is awesome!

2024-03-20 14:31 UTC, agustinesco approved these changes
LGTM! tested on the client and in an android build and the rotation worked great!

2024-03-20 14:32 UTC, merged