Fix death splash sprites
lambdaclass/curse_of_mirra pull request #1646
Opened 2024-04-03 03:24 UTC by AngieDutra

Closes #1609 

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-04-03 14:28 UTC, agustinesco commented on client/Assets/Scripts/UI/UIModelManager.cs
> +        if (characterName == "H4ck")
i'm not a huge fan of this approach, i think this will changed in the future when we implement a proper implementation for shadows (this is something mentioned in the pr description)

2024-04-03 14:31 UTC, agustinesco commented on client/Assets/Scripts/UI/UIModelManager.cs
> +                bool hasAnimationParameter = AnimationHasParameter(animationName);
The method `AnimationHasParameter/1` is used only here and the passed to the method `HandleAnimation/2`, i think we should delete this method and include the check for the existence of the animation in the `HandleAnimation` method

2024-04-03 14:32 UTC, agustinesco commented on client/Assets/Scripts/UI/UIModelManager.cs
> +    public void ShowCharacterAnimation()
I think we should rename this since we're not showing any animation, we are showing the end of game animation, maybe `ShowEndGameCharacterAnimation` is more suitable

2024-04-03 14:38 UTC, agustinesco commented on client/Assets/Images/UI/BattleUI/EndGame/reference defeated new.jpg
I'm pretty sure this is not supposed to be here right?

2024-04-03 14:53 UTC, agustinesco commented
The shadows seems to be working as expected, nice! i have one question tho, why are we using different shadows for the character info and the end game screen? 

End game: 
<img width="225" alt="image" src="https://github.com/lambdaclass/curse_of_mirra/assets/106101218/f8f3a718-ef7c-4118-9229-1c52234016b6">

Character info:
<img width="249" alt="image" src="https://github.com/lambdaclass/curse_of_mirra/assets/106101218/80c4733d-de00-43f5-b6cc-d98c92b22af2">

The character info one has some kind of blur at the end and the one from the end screen doesn't

2024-04-03 17:19 UTC, BertovDev commented on client/Assets/Scripts/UI/UIModelManager.cs
> +                bool hasAnimationParameter = AnimationHasParameter(animationName);
Yep, i like this approach

2024-04-03 17:30 UTC, BertovDev commented on client/Assets/Scripts/UI/UIModelManager.cs
> +    public void ShowCharacterAnimation()
Yes this is correct, since we already have another method to play the animations in the characterInfo (`AnimateCharacter/1`). Also makes me think of a possible refactor to unify them.

2024-04-03 17:32 UTC, BertovDev commented on client/Assets/Images/UI/BattleUI/EndGame/reference defeated new.jpg
Nope, deleting it now.

2024-04-03 18:06 UTC, BertovDev commented on client/Assets/Scripts/UI/UIModelManager.cs
> +        if (characterName == "H4ck")
Yep, not a big fan also. I changes it adding a scale values of each character shadow in the character ScriptableObject and then assign it by script. 

Let me know if you see it better.

2024-04-03 18:49 UTC, agustinesco commented on client/Assets/Scripts/UI/UIModelManager.cs
> +        bool hasAnimationParameter = AnimationHasParameter(animationName);
what i meant was to delete the `AnimationHasParamerter` method, the end result would be something like:
```suggestion
        bool hasAnimationParameter = modelAnimator
            .parameters
            .ToList()
            .Any(p => p.name == parameterName);
```

2024-04-03 18:51 UTC, agustinesco commented
I think the scale of the shadow is not quite right now

<img width="622" alt="image" src="https://github.com/lambdaclass/curse_of_mirra/assets/106101218/60e9b781-ad08-41a2-b6fc-b83ec1dfa5e1">

2024-04-03 18:59 UTC, agustinesco commented on client/Assets/Scripts/UI/UIModelManager.cs
> +
Obliterate this

```suggestion
```

2024-04-03 20:39 UTC, agustinesco commented on client/Assets/Scripts/UI/UIModelManager.cs
> +        bool hasAnimationParameter = modelAnimator.parameters.ToList().Find(anim => anim.name == animationName) != null;
i think using `Any` is cleaner than comparing with null right?

```suggestion
        bool hasAnimationParameter = modelAnimator.parameters.ToList().Any(anim => anim.name == animationName);
```

2024-04-08 14:27 UTC, agustinesco commented on client/Assets/Scripts/UI/UIModelManager.cs
> +        if (characterName == "H4ck")
hmmm yeah i think that may work

2024-04-08 14:38 UTC, agustinesco approved these changes
LGTM! tested on the unity editor and in an android build

2024-04-08 15:25 UTC, AngieDutra commented
Awesome, will review now ✨

2024-04-08 16:06 UTC, AngieDutra commented
All done! The model and shadow were in a weird position and scale. I adjusted that and checked Valtimer since he is now in main

2024-04-08 21:36 UTC, agustinesco requested changes
![image](https://github.com/lambdaclass/curse_of_mirra/assets/106101218/3db6def6-f556-489e-abfa-a406a7c1f37b)

i think the models are flying in the end screen, tested in the simulator with the google pixel 5

2024-04-08 21:36 UTC, AngieDutra commented
There is a responsive error reported in issue #1645 but I think I know how to fix this. Will try to do it here to avoid bugs in main

2024-04-09 18:15 UTC, AngieDutra commented
I did a small fix also solving issue #1645 but this should be refactor. Therefore, I'll leave the issue open to address this later on. For now I believe this approach works until the refactor takes priority

2024-04-09 19:13 UTC, BertovDev requested changes
Responsiveness seems to be working well! just a small comment.

2024-04-09 19:13 UTC, BertovDev commented on client/Assets/Scripts/UI/UIModelManager.cs
> +        }
I do not like this approach of let the others SerializeFields in null it seems like somethings is missing. Instead if you want these change only for the death Splash you can do the same thing but in `EndGameManager`.

What do you think?

2024-04-09 19:20 UTC, AngieDutra commented on client/Assets/Scripts/UI/UIModelManager.cs
> +        }
I dont think that's the solution to the issue you mention. We could add a bool to have the input field be hidden or visible but I believe it should be in the model manager in the final refactor. wdyt about this approach?

2024-04-09 19:32 UTC, BertovDev commented on client/Assets/Scripts/UI/UIModelManager.cs
> +        }
Yep this could be another solution. Nice

2024-04-10 18:58 UTC, agustinesco submitted a review, later dismissed
LGTM! the model seems to be correct in the two mobile version that you commented

2024-04-11 18:17 UTC, BertovDev approved these changes
Nice!! 

Death splash will be fixed in https://github.com/lambdaclass/curse_of_mirra/issues/1645

2024-04-11 18:32 UTC, AngieDutra commented
Let me check something with our TL before merging this

2024-04-17 15:04 UTC, AngieDutra commented
The character shadow in the death splash gives away our responsive position issue. The shadow was taken out of this PR and we will look into this later on. I did this [issue](https://github.com/lambdaclass/curse_of_mirra/issues/1684) to keep track

2024-04-17 15:42 UTC, BertovDev approved these changes
LGTM

2024-04-18 18:29 UTC, alfopisano approved these changes
Awesome!! Tested on iOS build and Unity desktop

2024-04-18 18:29 UTC, merged