[VFX] Added Magic Boots effect
lambdaclass/curse_of_mirra pull request #1652
Opened 2024-04-05 10:45 UTC by DmytroTkachukPingleStudio

## Motivation

Added Magic Boots effect  with scene for testing this effect.

## Summary of changes

- added Magic Boots effect
- added new scene for testing this effect

## How has this been tested?

Effect can be tested via test scene using cheat panel

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-04-09 18:07 UTC, BertovDev requested changes
Items VFX looking good so far!! and only we are having some troubles with this PR. 

The current `MagicBootsVFX` prefab is not working. After entering in the vfx graph and recompiling it we make it appear but it does not look as expected.

If we are missing something please let me know.


https://github.com/lambdaclass/curse_of_mirra/assets/62818001/64627623-9e05-4f69-b093-89f063093003

2024-04-10 06:29 UTC, DmytroTkachukPingleStudio commented
I've added missing assets, so now the effect should look as expected.

2024-04-10 14:17 UTC, BertovDev commented
> I've added missing assets, so now the effect should look as expected.

Nice! thank you.

2024-04-10 14:19 UTC, BertovDev approved these changes

2024-04-10 14:19 UTC, merged