Functionality to leave matchmaking
lambdaclass/curse_of_mirra pull request #1664
Opened 2024-04-09 19:32 UTC by AminArria

Closes #[issue]

## Motivation

Allow player to leave matchmaking

## Summary of changes

- [x] Add functionality to leave matchmaking
- [ ] Button in UI to trigger leave

## How has this been tested?

Test with https://github.com/lambdaclass/mirra_backend/pull/456

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-04-10 16:52 UTC, AngieDutra commented
Nice! I'll review this now

2024-04-10 23:54 UTC, AngieDutra commented
Client seems to work but I commented a bug in backend PR

2024-04-19 13:33 UTC, AngieDutra approved these changes
Awesome. Tested on Android build ✨

2024-04-19 19:02 UTC, alfopisano submitted a review, later dismissed
Nice!! Tested on iOS build

2024-04-29 16:29 UTC, Nico-Sanchez submitted a review, later dismissed

2024-04-29 22:01 UTC, AngieDutra commented
I had a weird thing happen. I was playing with Android build and Unity desktop. I canceled the first match with desktop and everything worked fine. But for the second match I wasn't able to join with my Unity desktop. It got stuck in the loading screen of prepare for battle. The fight image. However, I was able to see my desktop player in my game

2024-04-30 08:12 UTC, manucamejo requested changes

2024-04-30 08:12 UTC, manucamejo commented on client/Assets/Scripts/LobbyManager.cs
> +        if(System.String.IsNullOrEmpty(ServerConnection.Instance.GameSession)){
I'm not sure if this is correct; perhaps we should wait for the server's response before sending the player to the MainScreen.

2024-05-02 18:24 UTC, AminArria commented on client/Assets/Scripts/LobbyManager.cs
> +        if(System.String.IsNullOrEmpty(ServerConnection.Instance.GameSession)){
Done, now we receive a message for asking to leave and the response for it

2024-05-08 16:32 UTC, agustinesco approved these changes
LGTM! tested in both the unity client and in an android build and worked as expected!

this was recorded in android:
https://github.com/lambdaclass/curse_of_mirra/assets/106101218/ee3c3eed-7eb0-4ce9-98d3-aad0333b9f4f

2024-05-08 21:25 UTC, AngieDutra commented
I think the quick game button is broken in this PR

2024-05-09 21:19 UTC, AngieDutra approved these changes
Tested on Android build and is working as expected.
In the future re-design I would notice that the cancel button is in a similar position than the play button and this may not be wat we want in our UX

2024-05-09 21:19 UTC, merged