[GH-1669] Replace power up object
lambdaclass/curse_of_mirra pull request #1672
Opened 2024-04-11 17:30 UTC by alfopisano

Closes #1669

## Motivation
We need to replace the power up object with its new version 

## Summary of changes
- Replaced the old object with the new asset. 
- Deleted the now unused power up. 

## How has this been tested?

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-04-11 18:33 UTC, BertovDev commented on client/Assets/Prefabs/Projectiles/HackSlingshot.prefab
Checkout this.

2024-04-11 18:38 UTC, BertovDev requested changes
Everything seem to be working well and just delete the unwanted files. 

One more thing, did you follow any reference for the scale of the prefab? if not, I will decrease it a little bit like 0.6 in each axis.

btw I like the explanation for each commit.

2024-04-11 18:38 UTC, BertovDev commented on client/Assets/Prefabs/Projectiles/HackSlingshot.prefab
Checkout this.

2024-04-11 18:38 UTC, BertovDev commented on client/Assets/Resources/Fonts/SourceSans3-Bold SDF.asset
And also this.

2024-04-11 19:27 UTC, alfopisano commented on client/Assets/Prefabs/Projectiles/HackSlingshot.prefab
Oh sorry!! Nice catch 🙌

2024-04-11 19:27 UTC, alfopisano commented on client/Assets/Resources/Fonts/SourceSans3-Bold SDF.asset
Same as above.

2024-04-11 19:29 UTC, alfopisano commented
> Everything seem to be working well and just delete the unwanted files.
> 
> One more thing, did you follow any reference for the scale of the prefab? if not, I will decrease it a little bit like 0.6 in each axis.
> 
> btw I like the explanation for each commit.

I did not follow any reference for scaling the prefab but I agree with you, it looks a little too big in comparison with the character's size.

2024-04-11 20:25 UTC, alfopisano commented
I tried scaling the power up on 0.6 and it looks much better now!! 

And btw sorry for all the commits, I got really messed up trying to restore the fonts and slingshot files 😅

2024-04-11 21:06 UTC, BertovDev commented
> I tried scaling the power up on 0.6 and it looks much better now!!
> 
> And btw sorry for all the commits, I got really messed up trying to restore the fonts and slingshot files 😅

No worriess, we should merge https://github.com/lambdaclass/curse_of_mirra/pull/1667 asap

2024-04-11 21:06 UTC, BertovDev approved these changes
LGTM

Tested on Android S23

2024-04-11 22:55 UTC, AngieDutra commented
I think the aura of the orbe is too big. I think the overall look would benefit from making the amokey effect of the orbe smaller

2024-04-15 18:19 UTC, BertovDev approved these changes
Well done, looking good to me.

Tested on Xiomi redmi note 9S and Samsung s23

2024-04-15 19:07 UTC, AngieDutra approved these changes
Nice! Tested in Android build

2024-04-15 19:07 UTC, merged