Camera settings
lambdaclass/curse_of_mirra pull request #1704
Opened 2024-04-19 21:59 UTC by AngieDutra

## Motivation

Camera needed more setting options

## Summary of changes

Tis PR adds perspective settings:
- Zoom in
- Zoom out
- Default
- Sentinel 

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-04-22 17:27 UTC, alfopisano requested changes
Nice!! I just have a question, when on the sentinel camera I can not see the health bars, is that alright? 

https://github.com/lambdaclass/curse_of_mirra/assets/116388676/70d99b59-6119-44d0-87d2-2eae5b41f62f

2024-04-22 18:55 UTC, AngieDutra commented
Our PM said he'll create an issue for this and we should move on if this is the only thing found so far

2024-04-22 18:56 UTC, alfopisano commented
As discussed with the team, we should leve it as it is for now and approach it on future iterations.

2024-04-22 18:56 UTC, alfopisano submitted a review, later dismissed

2024-04-22 19:07 UTC, BertovDev requested changes
Nice working good and I am not a big fan of creating classes to only holding a reference. Instead I would do something like this. Wdyt?

2024-04-22 19:07 UTC, BertovDev commented on client/Assets/Scripts/UI/CameraManager.cs
> +    GameObject mainCameraCM;
```
    [SerializeField] 
    CinemachineVirtualCamera mainCameraCM;
```

2024-04-22 19:07 UTC, BertovDev commented on client/Assets/Scripts/UI/CameraManager.cs
> +        initialCameraDistance = mainCameraCM.GetComponent<CinemachineVirtualCamera>().GetCinemachineComponent<CinemachineFramingTransposer>().m_CameraDistance;
```
        cinemachineFramingTransposer = mainCameraCM.GetCinemachineComponent<CinemachineFramingTransposer>();
        initialCameraDistance = cinemachineFramingTransposer.m_CameraDistance;
```

2024-04-22 19:07 UTC, BertovDev commented on client/Assets/Scripts/UI/CameraManager.cs
> +        mainCameraCM.GetComponent<CinemachineVirtualCamera>().GetCinemachineComponent<CinemachineFramingTransposer>().m_CameraDistance = cameraDistance;
`       cinemachineFramingTransposer.m_CameraDistance = cameraDistance;`

2024-04-22 19:48 UTC, AngieDutra commented
I'll try this then

2024-04-22 20:40 UTC, AngieDutra commented
Everything was added or changed as solicited

2024-04-23 11:36 UTC, BertovDev approved these changes
LGTM

Tested on Android s23

2024-04-23 16:41 UTC, alfopisano approved these changes
Nice!! Tested on iOS build

2024-04-23 16:41 UTC, merged