[GH-1682] Add functionality to quests screen
lambdaclass/curse_of_mirra pull request #1740
Opened 2024-04-30 20:42 UTC by alfopisano

Issue #1682

## Motivation
Now that the we have the quests screen created we need to add functionality to it: 
- When completed change to _ready to claim_ version. 
- When claiming a completed quest the reward should be added to the total of trophies.
- When pushing the reroll button the available quests for reroll should be highlighted. 
- When pushing the finish button the quests should look like in the beginning. 
- Show actual amount of quests available for reroll.

## Summary of changes

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-06 21:05 UTC, jazimp requested changes
In the Reroll section, the white glow is missing on the hexagon of the quest that is available for reroll

2024-05-07 13:23 UTC, alfopisano commented
> I'm not sure if it's an error due to the quality of the image or the implementation, but I think the progress bars for each quest are distorted (the right tip)

You are right. I think it is due to the stretching for representing the progress. I would do some research on how to avoid this!!

2024-05-07 15:35 UTC, jazimp commented
Sorry, I meant to say "After rerolling a quest" instead of "Reroll section". I was referring to the hexagon with the image of H4ck (in this case)
Implementation vs Design: 
<img width="419" alt="Captura de pantalla 2024-05-07 a la(s) 12 34 41" src="https://github.com/lambdaclass/curse_of_mirra/assets/134973476/2ba1b890-2614-46a2-9551-7a3eed980bde">
<img width="560" alt="Captura de pantalla 2024-05-07 a la(s) 12 35 06" src="https://github.com/lambdaclass/curse_of_mirra/assets/134973476/62c41b87-f943-4d79-8d60-de5cc8a301eb">

2024-05-08 17:20 UTC, alfopisano commented
I would now make some changes regarding the performance and understanding of the code added.

2024-05-13 16:28 UTC, BertovDev requested changes
Really nice and also some minor changes.

- Check the position of the first image in the quest1. It is different from others.

<img width="1437" alt="Screenshot 2024-05-13 at 1 08 31 PM" src="https://github.com/lambdaclass/curse_of_mirra/assets/62818001/abe9b5ca-55c9-442c-9389-b4d1d2debf25">

- Notice that the ready to claim container is not clickeable for reclaiming the quest. This is because is a slider and it is set as no interactable. We can do a workaround this or change to a image with a fill type.

2024-05-13 16:28 UTC, BertovDev commented on client/Assets/Scripts/UI/Quest.cs
> +    public int reward;
Variables like this where you only access it in the same script can be set as `private` and add the 
`[SerializeField] ` tag to access them from unity. Correct them if you can.

2024-05-13 16:28 UTC, BertovDev commented on client/Assets/Scripts/UI/QuestsManager.cs
> +        foreach (Quest q in quests)
We could change the `q` to `quest` it is just a readability and standard things. Wdyt?

2024-05-13 16:52 UTC, alfopisano commented on client/Assets/Scripts/UI/Quest.cs
> +    public int reward;
Done!!

2024-05-13 16:53 UTC, alfopisano commented on client/Assets/Scripts/UI/QuestsManager.cs
> +        foreach (Quest q in quests)
Done!!

2024-05-13 19:21 UTC, BertovDev approved these changes
Awesome work

2024-05-13 20:35 UTC, jazimp approved these changes

2024-05-13 20:42 UTC, AngieDutra approved these changes
Awesome! 
My only comment is this container may be too small but for now it works.
Checked the responsiveness and is awesome too!
<img width="100" alt="Screenshot 2024-05-13 at 17 38 54" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/fa77fb5c-7d36-40c4-8fec-c31d037acebe">

2024-05-13 20:42 UTC, merged