Add spectate mode
lambdaclass/curse_of_mirra pull request #1744
Opened 2024-05-03 15:11 UTC by BertovDev

Closes #156 

## Motivation

Add spectate mode

## Summary of changes

Added new button.

## How has this been tested?

Describe the steps you performed to test this PR.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-03 21:19 UTC, AngieDutra reviewed
Here is the visual reference @jazimp 

https://github.com/lambdaclass/curse_of_mirra/assets/82987608/68d696eb-5d24-4037-b501-6a0b03151481

2024-05-03 21:37 UTC, jazimp submitted a review, later dismissed
I see these points to review in this implementation:

- The "defeated" text shouldn't overlap with the FPS and PING info.

- It's odd that the position of the "continue" button changes.

- Check that the typographic variable used in the buttons is consistent, (Source Sans 3 - Black).

2024-05-09 21:55 UTC, BertovDev commented
Uploading Screen Recording 2024-05-09 at 6.54.46 PM.mov…

2024-05-09 22:05 UTC, jazimp commented
visual approval ✅

2024-05-09 22:09 UTC, BertovDev commented
https://github.com/lambdaclass/curse_of_mirra/assets/62818001/d4e2d83e-3d55-42c4-8b32-b40a80a7b554

References:
![1](https://github.com/lambdaclass/curse_of_mirra/assets/62818001/779111d5-8ee9-4543-8832-f11fa241dffa)

![2](https://github.com/lambdaclass/curse_of_mirra/assets/62818001/9e78c205-3911-4560-ba80-4d7107a89f4b)

2024-05-09 22:26 UTC, AngieDutra requested changes
Other than that is working as expected. It would be nice to add some animation otr transition opacity for level it up but for now it works and we can move on 👍🏼

2024-05-09 22:26 UTC, AngieDutra commented on client/Assets/Resources/Fonts/SourceSans3-Bold SDF.asset
This should not be pushed

2024-05-10 19:15 UTC, AngieDutra approved these changes
Tested on Android build and is working as expected

2024-05-10 19:19 UTC, tvillegas98 approved these changes
The spectate mode seems to work well!

2024-05-10 19:22 UTC, merged