Add dynamic lobby tips.
lambdaclass/curse_of_mirra pull request #1748
Opened 2024-05-06 20:48 UTC by BertovDev

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-09 18:19 UTC, alfopisano submitted a review, later dismissed
Nice!! Tested on unity desktop and iOS build and looks great

2024-05-09 22:44 UTC, AngieDutra requested changes

2024-05-09 22:44 UTC, AngieDutra commented on client/Assets/Resources/tips.json
Just looked at the code and saw this newline, it should be fixed
<img width="208" alt="Screenshot 2024-05-09 at 19 40 36" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/10614ab4-714d-41dd-9f68-ab14dc3cbb00">

2024-05-10 14:32 UTC, jazimp commented
visual approval ✅

2024-05-10 16:20 UTC, alfopisano submitted a review, later dismissed
Nice!! Tested on iOS build and everything seemed to work as expected

2024-05-10 17:08 UTC, AngieDutra requested changes

2024-05-10 17:08 UTC, AngieDutra commented on client/Assets/Scripts/GameNavigationManager.cs
> +                    var genetalTip = charactersData.characters.Last();
```suggestion
                    var generalTip = charactersData.characters.Last();
```

2024-05-10 19:05 UTC, AngieDutra approved these changes
Tested in Android build and is working as expected

2024-05-10 19:21 UTC, mgrunwaldt commented on client/Assets/Resources/tips.json
> +            "Use Golden Clock to charge your ult and reset all cooldowns!"
```suggestion
            "Use Golden Clock to charge your ulti and reset all cooldowns!"
```

2024-05-10 19:23 UTC, mgrunwaldt approved these changes

2024-05-10 19:25 UTC, AngieDutra commented on client/Assets/Resources/tips.json
> +            "Use Myrra's Blessing and become immune to all damage!",
```suggestion
            "Use Mirra's Blessing and become immune to all damage!",
```

2024-05-10 19:28 UTC, mgrunwaldt approved these changes

2024-05-10 19:29 UTC, AngieDutra approved these changes
Awesome

2024-05-10 19:29 UTC, merged