Fix movement block in battle init
lambdaclass/curse_of_mirra pull request #1763
Opened 2024-05-14 21:45 UTC by BertovDev

## Motivation

Fix first movement.

## Summary of changes

Change time freezing player movement.

## How has this been tested?

Start a game check if you can move in the moment the Battle init animation disappear. 

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-15 15:03 UTC, AngieDutra requested changes

2024-05-15 15:03 UTC, AngieDutra commented on client/Assets/Scripts/UI/PrepareForBattleAnimations.cs
> +        print("You can move now");
delete this

2024-05-15 18:13 UTC, AngieDutra approved these changes
Nice one. It can now be moved by the keyboard but I think this is related to back

2024-05-16 17:19 UTC, alfopisano approved these changes
Nice!! Tested iOS build and worked as expected

2024-05-16 17:19 UTC, merged