Fix signin meta changes
lambdaclass/curse_of_mirra pull request #1773
Opened 2024-05-16 14:49 UTC by AngieDutra

## Motivation

If you go to main and then to Unity, this will happen:
<img width="1205" alt="Screenshot 2024-05-16 at 11 41 47" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/f64d4fb3-8159-47ff-8414-f34cf34249c7">

## Summary of changes

This PR adds those files that should have been added when a folder was deleted

## How has this been tested?

Try going to main then to unity.
You should se those changes.
Run `git restore .`
Now in this branch go to unity.
Those files should not be there anymore.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-16 15:07 UTC, tvillegas98 commented
Tested on Android and this files doesn't not seem to appear

2024-05-16 15:10 UTC, tvillegas98 submitted a review, later dismissed

2024-05-16 15:22 UTC, Nico-Sanchez requested changes
I don't have this issue. Could it be that you don't have `cocoapods` dependency?

2024-05-16 21:57 UTC, Nico-Sanchez approved these changes

2024-05-16 21:58 UTC, Nico-Sanchez commented
It's working fine now, we should make sure everyone has the same config and we don't see this changes.
@AngieDutra please create an issue to add the unity config in the readme.

2024-05-17 14:21 UTC, tvillegas98 approved these changes

2024-05-17 14:21 UTC, merged